from xpinyin import Pinyin
p = Pinyin()
pinyin = p.get_pinyin( '刘纲','' )
print(pinyin)
pinyin = p.get_pinyin( '蒋晓云','' )
print(pinyin)
pinyin = p.get_pinyin( '吴晓芳','' )
print(pinyin)
pinyin = p.get_pinyin( '左玮','' )
print(pinyin)
pinyin = p.get_pinyin( '蔡力健','' )
print(pinyin)
pinyin = p.get_pinyin( '宋娜','' )
print(pinyin)
pinyin = p.get_pinyin( '唐成','' )
print(pinyin)
pinyin = p.get_pinyin( '王超','' )
print(pinyin)
pinyin = p.get_pinyin( '胡天波','' )
print(pinyin)
pinyin = p.get_pinyin( '杨芬','' )
print(pinyin)
pinyin = p.get_pinyin( '张鹏','' )
print(pinyin)
pinyin = p.get_pinyin( '聂琼','' )
print(pinyin)
pinyin = p.get_pinyin( '汤敏','' )
print(pinyin)
pinyin = p.get_pinyin( '周维娜','' )
print(pinyin)
pinyin = p.get_pinyin( '韩萍','' )
print(pinyin)
pinyin = p.get_pinyin( '褚捷','' )
print(pinyin)
pinyin = p.get_pinyin( '向东','' )
print(pinyin)
pinyin = p.get_pinyin( '王慧','' )
print(pinyin)
pinyin = p.get_pinyin( '黄文华','' )
print(pinyin)
pinyin = p.get_pinyin( '孙倩','' )
print(pinyin)
pinyin = p.get_pinyin( '白帆','' )
print(pinyin)
pinyin = p.get_pinyin( '张旋','' )
print(pinyin)
pinyin = p.get_pinyin( '罗峰','' )
print(pinyin)
pinyin = p.get_pinyin( '王晶','' )
print(pinyin)
pinyin = p.get_pinyin( '戚勇','' )
print(pinyin)
pinyin = p.get_pinyin( '柳俊','' )
print(pinyin)
pinyin = p.get_pinyin( '刘钢','' )
print(pinyin)
pinyin = p.get_pinyin( '郭辉','' )
print(pinyin)
pinyin = p.get_pinyin( '桂四海','' )
print(pinyin)
pinyin = p.get_pinyin( '肖作武','' )
print(pinyin)
pinyin = p.get_pinyin( '徐弢','' )
print(pinyin)
pinyin = p.get_pinyin( '韩守懿','' )
print(pinyin)
pinyin = p.get_pinyin( '李勇','' )
print(pinyin)
pinyin = p.get_pinyin( '李凌','' )
print(pinyin)
pinyin = p.get_pinyin( '刘军','' )
print(pinyin)
pinyin = p.get_pinyin( '刘嘉欣','' )
print(pinyin)
pinyin = p.get_pinyin( '项军','' )
print(pinyin)
pinyin = p.get_pinyin( '向衡','' )
print(pinyin)
pinyin = p.get_pinyin( '章磊','' )
print(pinyin)
pinyin = p.get_pinyin( '李文贵','' )
print(pinyin)
pinyin = p.get_pinyin( '颜军','' )
print(pinyin)
pinyin = p.get_pinyin( '陈国龙','' )
print(pinyin)
pinyin = p.get_pinyin( '严纪云','' )
print(pinyin)
pinyin = p.get_pinyin( '董春一','' )
print(pinyin)
pinyin = p.get_pinyin( '李祖红','' )
print(pinyin)
pinyin = p.get_pinyin( '王分容','' )
print(pinyin)
pinyin = p.get_pinyin( '史训权','' )
print(pinyin)
pinyin = p.get_pinyin( '吴坤','' )
print(pinyin)
pinyin = p.get_pinyin( '冯义升','' )
print(pinyin)
pinyin = p.get_pinyin( '李智力','' )
print(pinyin)
pinyin = p.get_pinyin( '张旋','' )
print(pinyin)
pinyin = p.get_pinyin( '邱俊','' )
print(pinyin)
pinyin = p.get_pinyin( '汪頔','' )
print(pinyin)
pinyin = p.get_pinyin( '褚亮','' )
print(pinyin)
pinyin = p.get_pinyin( '王峰','' )
print(pinyin)
pinyin = p.get_pinyin( '尉超','' )
print(pinyin)
pinyin = p.get_pinyin( '梁峰','' )
print(pinyin)
pinyin = p.get_pinyin( '孙涛','' )
print(pinyin)
pinyin = p.get_pinyin( '郭巍立','' )
print(pinyin)
pinyin = p.get_pinyin( '李伟长','' )
print(pinyin)
pinyin = p.get_pinyin( '曹巍','' )
print(pinyin)
pinyin = p.get_pinyin( '王磊','' )
print(pinyin)
pinyin = p.get_pinyin( '李浩','' )
print(pinyin)
pinyin = p.get_pinyin( '王瑾','' )
print(pinyin)
pinyin = p.get_pinyin( '张尉','' )
print(pinyin)
pinyin = p.get_pinyin( '张伟','' )
print(pinyin)
pinyin = p.get_pinyin( '潘厚峰','' )
print(pinyin)
pinyin = p.get_pinyin( '陈实','' )
print(pinyin)
pinyin = p.get_pinyin( '李文建','' )
print(pinyin)
pinyin = p.get_pinyin( '张磊','' )
print(pinyin)
pinyin = p.get_pinyin( '陈刚','' )
print(pinyin)
pinyin = p.get_pinyin( '吴波','' )
print(pinyin)
pinyin = p.get_pinyin( '冯凯','' )
print(pinyin)
pinyin = p.get_pinyin( '熊磊','' )
print(pinyin)
pinyin = p.get_pinyin( '陈赞','' )
print(pinyin)
pinyin = p.get_pinyin( '江澍泽','' )
print(pinyin)
pinyin = p.get_pinyin( '王冠勋','' )
print(pinyin)
pinyin = p.get_pinyin( '娄力奇','' )
print(pinyin)
pinyin = p.get_pinyin( '史浩楠','' )
print(pinyin)
pinyin = p.get_pinyin( '胡毅','' )
print(pinyin)
pinyin = p.get_pinyin( '李密','' )
print(pinyin)
pinyin = p.get_pinyin( '王立成','' )
print(pinyin)
pinyin = p.get_pinyin( '牛猛','' )
print(pinyin)
pinyin = p.get_pinyin( '杜田义','' )
print(pinyin)
pinyin = p.get_pinyin( '徐吉','' )
print(pinyin)
pinyin = p.get_pinyin( '李国胜','' )
print(pinyin)
pinyin = p.get_pinyin( '谷清华','' )
print(pinyin)
pinyin = p.get_pinyin( '罗露','' )
print(pinyin)
pinyin = p.get_pinyin( '凃睿','' )
print(pinyin)
pinyin = p.get_pinyin( '郑汉平','' )
print(pinyin)
pinyin = p.get_pinyin( '张勇','' )
print(pinyin)
pinyin = p.get_pinyin( '龙昌勤','' )
print(pinyin)
pinyin = p.get_pinyin( '调度室','' )
print(pinyin)
pinyin = p.get_pinyin( '甄庆元','' )
print(pinyin)
pinyin = p.get_pinyin( '杨明','' )
print(pinyin)
pinyin = p.get_pinyin( '徐波','' )
print(pinyin)
pinyin = p.get_pinyin( '王志翔','' )
print(pinyin)
pinyin = p.get_pinyin( '刘建平','' )
print(pinyin)
pinyin = p.get_pinyin( '肖国洲','' )
print(pinyin)
pinyin = p.get_pinyin( '杨伟华','' )
print(pinyin)
pinyin = p.get_pinyin( '刘涛','' )
print(pinyin)
pinyin = p.get_pinyin( '曾祥龙','' )
print(pinyin)
pinyin = p.get_pinyin( '李定国','' )
print(pinyin)
pinyin = p.get_pinyin( '邹银','' )
print(pinyin)
pinyin = p.get_pinyin( '陆众丹','' )
print(pinyin)
pinyin = p.get_pinyin( '吴键','' )
print(pinyin)
pinyin = p.get_pinyin( '罗琦','' )
print(pinyin)
pinyin = p.get_pinyin( '许霁伟','' )
print(pinyin)
pinyin = p.get_pinyin( '张杰','' )
print(pinyin)
pinyin = p.get_pinyin( '张伟','' )
print(pinyin)
pinyin = p.get_pinyin( '李刚','' )
print(pinyin)
pinyin = p.get_pinyin( '奚君伟','' )
print(pinyin)
pinyin = p.get_pinyin( '李强','' )
print(pinyin)
pinyin = p.get_pinyin( '王倪倪','' )
print(pinyin)
pinyin = p.get_pinyin( '杨兴','' )
print(pinyin)
pinyin = p.get_pinyin( '严必亮','' )
print(pinyin)
pinyin = p.get_pinyin( '陈长雄','' )
print(pinyin)
pinyin = p.get_pinyin( '曾新','' )
print(pinyin)
pinyin = p.get_pinyin( '朱双艳','' )
print(pinyin)
