# Generated by Selenium IDE
from time import sleep
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class User:
    global driver
    driver=webdriver.Chrome()
    def __init__(self):
        driver.implicitly_wait(20)
        driver.get("http://192.168.10.195:7799/")
        # 刷新当前界面，清除历史数据
        driver.refresh()
        sleep(2)
        # 2 | setWindowSize | 1550x848 |
        driver.set_window_size(1550, 848)
        sleep(1)
        driver.maximize_window()
        driver.implicitly_wait(20)
    def setup_method(self):
        pass

    def teardown_method(self):
        pass

    def login(self, username, password):
        sleep(2)
        driver.find_element_by_name("username").click()
        sleep(2)
        # 4 | type | name=username | admin
        driver.find_element_by_name("username").send_keys(username)
        sleep(1)
        # 5 | click | name=password |
        driver.find_element_by_name('password').click()
        sleep(2)
        # 6 | type | name=password | 123456
        driver.find_element_by_name("password").send_keys(password)
        # 7 | click | css=.suffix-icon |
        driver.find_element_by_css_selector(".suffix-icon").click()
        sleep(2)
        # 8 | click | css=button |
        driver.find_element_by_css_selector("button").click()
        sleep(2)

    ##  制定方案
    def make_scheme(self, fa_name, fw_name):
        xjgl = driver.find_element_by_xpath('//div/span[@title="巡检管理"]')
        ##鼠标事件 虚浮在元素上方
        ActionChains(driver).move_to_element(xjgl).perform()
        xjfazd = driver.find_element(By.XPATH,
            '//span[text()="巡检方案制定"]')
        ActionChains(driver).click(xjfazd).perform()
        sleep(2)
        driver.implicitly_wait(20)
        ##创建方案
        jh_name = fa_name
        print('请输入方案名称')
        driver.find_element_by_xpath('//input[@placeholder="请输入方案名称"]').send_keys(fa_name)
        sleep(2)
        print('点击筛选')
        sx = driver.find_element_by_xpath('//div/a/img[@src="/images/filter.svg"]')
        ActionChains(driver).click(sx).perform()
        sleep(2)
        print('查询范围输入')
        driver.find_element(By.XPATH,"//span[text()='查询范围：']/../span[@class='ant-select ant-select-enabled ant-select-allow-clear']").send_keys('04-开关阀组')
        sleep(2)
        print('点击搜索')
        fw = driver.find_element_by_xpath(
            '//*[@id="baseInfo"]/div[4]/div[1]/div[1]/div[2]/i[1]/svg/path')
        ActionChains(driver).click(fw).perform()
        sleep(2)
        ##  随机点击页面 body > div.container-fluid > div.row
        driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/input').click()
        sleep(2)
        ##搜索
        driver.find_element_by_css_selector('#buttonPanel > input.button.base-button-query-style').click()
        sleep(2)
        ##选择设备
        driver.find_element_by_css_selector(
            '#datagrid-row-r2-2-1 > td:nth-child(1) > div > input[type=checkbox]').click()
        ##点击确定，回到制定界面
        driver.find_element_by_css_selector('#return-bt > input.button.retrieval-button.base-button-save-style').click()
        ##有效范围#workscope2 > xm-select > div.xm-label.single-row
        driver.find_element_by_css_selector('#workscope2 > xm-select > div.xm-label.single-row').click()
        ##备注
        sleep(2)
        driver.find_element_by_css_selector('#form-schemeRemark').send_keys('chenziran')
        ##上报#attachmentfile > div > div:nth-child(1) > div > a > img
        ##保存#saveBut
        driver.find_element_by_css_selector('#saveBut').click()
        ##跳到最外层的页面
        driver.switch_to.default_content()
        driver.find_element_by_css_selector(
            'body > div.v-dialog.v-s-normal.v-t-confirm > div.v-dialog-footer.v-s-center > div.v-dialog-footer-btn.v-dialog-footer-btn-cancel').click()

    def make_plan(self,fa_name, ry_name):
        jh_name = fa_name
        xjgl = driver.find_element_by_xpath('//*[@id="main"]/div[5]/div[2]/div[1]/div/div/div/div[3]/div/span[2]')
        ##鼠标事件 虚浮在元素上方
        ActionChains(driver).move_to_element(xjgl).perform()
        fagl = driver.find_element_by_xpath('/html/body/div[8]/div/div[2]/div/span[2]')
        ActionChains(driver).click(fagl).perform()
        sleep(2)
        driver.find_element_by_css_selector('#horizontal_SearchBar_field-schemeName').send_keys(fa_name)
        sleep(2)
        ##点击查询 #query
        driver.find_element_by_css_selector('#MAKE_PLAN_CZ > div > form > div > span.index__search_btn___1rRz_').click()
        ##点击分派
        sleep(2)
        driver.find_element_by_css_selector(
            '#MAKE_PLAN_CZ > div > div:nth-child(3) > div > div > div.ant-table-wrapper > div > div > div > div > div > div.ant-table-body > table > tbody > tr:nth-child(1) > td:nth-child(9) > a:nth-child(2)').click()
        sleep(2)
        ##切换到制定计划iframe
        jhfp = driver.find_element_by_css_selector(
            'body > div.v-dialog.v-s-normal > div.v-dialog-body > div > div > iframe')
        driver.switch_to.frame(jhfp)
        sleep(2)
        driver.find_element_by_css_selector('#taskName').send_keys(jh_name)
        sleep(2)
        ##人员选择 exeUserPerson
        driver.find_element_by_id('exeUserPerson').click()
        ##跳到最外层的页面
        driver.switch_to.default_content()
        sleep(2)
        ryxz = driver.find_element_by_css_selector('#layui-laydialog-iframe1')
        driver.switch_to.frame(ryxz)
        driver.find_element_by_css_selector('#fullname').send_keys(ry_name)
        driver.find_element_by_css_selector(
            '#tab-1 > div > div > div > table > tbody > tr > td:nth-child(2) > div.toolbar-panel > div > div.toolbar-head.clearfix > div:nth-child(1) > a > span').click()
        ##    选择人  //*[@id="854670074076725248"]/td[3]  #\38 54670074076725248 > td:nth-child(3)
        driver.find_element_by_xpath(
            '/html/body/div[1]/div[2]/div/div[1]/div/div/div/table/tbody/tr/td[2]/div[2]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[@title="陈自然"]').click()
        ##    patrol2
        ##    driver.find_element_by_xpath('//*[@id="854670074076725248"]/td[3]').click()
        sleep(2)
        driver.switch_to.default_content()
        driver.find_element_by_link_text('选择').click()
        sleep(2)
        driver.switch_to.frame(jhfp)
        driver.find_element_by_xpath('/html/body/div[1]/div[2]/input[1]').click()

    def make_ywpz(self):
        xtpz = driver.find_elements_by_xpath('//span[@title="系统设置"]')[0]
        # 将业务配置元素滑动到可见位置
        driver.execute_script('arguments[0].scrollIntoView()',xtpz)
        sleep(3)
        ActionChains(driver).move_to_element(xtpz).perform()
        driver.implicitly_wait(20)
        sleep(5)
        elements=driver.find_elements_by_tag_name('span')
        sleep(1)
        for element in elements:
            if element.text=='业务配置':
                print("点击业务配置")
                ActionChains(driver).click(element).perform()
                break
        sleep(2)
        print('进入业务配置')
        # 业务配置-查看
        driver.find_element_by_xpath('//td[text()="巡检"]/../td[3]/div/button[1]').click()
        print("进入业务配置列表")
        driver.find_element_by_xpath('//div[text()="+ 添加类型"]').click()
        sleep(4)
        driver.find_element_by_id('name').send_keys('测试')
        sleep(1)
        driver.find_element_by_id('code').send_keys('测试')
        sleep(1)
        gwz={'供水管网':['管段','节点','阀门']}
        for key in gwz.keys():
            for value in gwz[key]:
                # 添加作业对象
                driver.find_element_by_xpath("//label[text()='作业对象']/../button[1]").click()
                sleep(1)
                # 点击设备类型
                driver.find_element_by_xpath('//span[@class="ant-select-selection__rendered"]').click()
                sleep(3)
                # 选择设备
                driver.find_element(By.CSS_SELECTOR,"span[title='"+key+"']+ul span[title='"+value+"']").click()
                sleep(1)
                # 作业历史选择
                driver.find_element(By.XPATH,"//div[@id='historyRecords']/div/div[@class='ant-select-selection__rendered']").click()
                sleep(2)
                driver.find_element(By.XPATH,"//ul[ @role='listbox']/li[text()='设备作业历史']").click()
                sleep(2)
                # 到位
                driver.find_element(By.XPATH,"//span[text()='到位']").click()
                sleep(1)
                # 到位半径
                driver.find_element(By.XPATH,"//input[@role='spinbutton']").click()
                sleep(1)
                #是否反馈
                driver.find_element(By.XPATH,"//span[text()='反馈']").click()
                # 设备反馈
                driver.find_element(By.XPATH,"//div[@id='equipFeedbackBpm']/div/div[@class='ant-select-selection__rendered']").click()
                sleep(2)
                # 设备流程
                driver.find_element(By.XPATH,"//ul[@role='listbox']/li[text()='设备反馈']").click()
                sleep(1)
                # 保存
                driver.find_element(By.XPATH,"//span/div/button[@type='submit']").click()
                sleep(1)




