# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_(self):
    self.driver.get("http://10.41.16.20:32091/login?redirect=%2F")
    self.driver.set_window_size(1456, 916)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    self.driver.find_element(By.NAME, "password").send_keys("YSD@city")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".v-s-enter .v-menu-item-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-table-row:nth-child(1) .ant-btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".index__addStyle___3HMma").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("测试")
    self.driver.find_element(By.ID, "code").send_keys("测试")
    self.driver.find_element(By.CSS_SELECTOR, ".TabObject__header___3M4dR > .ant-btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-form-item-children path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-search__field").send_keys("管段")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-tree-treenode-disabled:nth-child(1) > .ant-select-tree-child-tree .ant-select-tree-node-content-wrapper").click()
    self.driver.find_element(By.CSS_SELECTOR, "#historyRecords svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-dropdown-menu-item-active").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-col-9 .ant-checkbox-inner").click()
    self.driver.find_element(By.CSS_SELECTOR, "#needArrive .ant-checkbox-input").click()
    self.driver.find_element(By.ID, "buffer").click()
    self.driver.find_element(By.ID, "buffer").send_keys("100")
    self.driver.find_element(By.CSS_SELECTOR, "#equipFeedbackBpm .ant-select-selection__rendered").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-select-dropdown-menu-item-active").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-form-item-children > div > .ant-btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-form-item-children > .ant-btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".x-tab-active > .x-tab-panel-body").click()
  
